# Rustfmt Configuration
# Following ADR-007: Rust Coding Standards and Latest Practices

edition = "2024"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

