[workspace]

[package]
name = "minimal-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.9", features = ["csr"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
